/**
 * Replace generated, security-sensitive files that older releases copied into
 * a project and never updated again.
 *
 * Why this exists (0.44.20): `setup` / `init` copied the MCP server and the
 * prompt hooks into each project ONLY IF THE FILE DID NOT EXIST. A fix in the
 * package therefore never reached anyone who had already installed — they kept
 * running the old, injectable MCP server and the old shell-based hooks after
 * `npm i -g infernoflow@latest`. This module overwrites those copies whenever
 * they differ from (MCP server) or predate (hooks) the shipped template.
 *
 * Scope: files INSIDE the project only. Never touches anything under `~`.
 * These files are generated by infernoflow; they are not meant to be edited.
 *
 * Called from `setup`, `init` (via autoSetupMcp) and the silent upgrade
 * backfill, so it runs on the first infernoflow command after an upgrade —
 * including the one the post-commit hook runs.
 */
import * as fs   from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** lib/securityRefresh.mjs → ../templates (repo) or dist/lib → dist/templates (shipped). */
function templatesRoot() {
  return path.resolve(__dirname, "../templates");
}

/** Marker line every current hook template carries. Bump with the hook code. */
export const HOOK_VERSION_MARKER = "infernoflow-hook-version: 2";

function readOrNull(p) {
  try { return fs.readFileSync(p, "utf8"); } catch { return null; }
}

/** Normalise line endings so a CRLF checkout of an identical file isn't "different". */
const norm = (s) => (s == null ? s : s.replace(/\r\n/g, "\n"));

/** Heuristic: is this file an infernoflow MCP server (any version)? */
function looksLikeInfernoflowServer(text) {
  return typeof text === "string" &&
    (text.includes('serverInfo: { name: "infernoflow"') || text.includes("[infernoflow MCP]"));
}

/**
 * @param {string} cwd project root
 * @param {object} [opts]
 * @param {string} [opts.captureHookScript] current Claude Code hook source
 *        (passed in by setup.mjs to avoid a circular import)
 * @returns {string[]} project-relative paths that were rewritten
 */
export function refreshSecuritySensitiveCopies(cwd, opts = {}) {
  const updated = [];
  const tmpl = templatesRoot();

  const rewrite = (rel, content) => {
    const abs = path.join(cwd, rel);
    try {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content, "utf8");
      updated.push(rel.split(path.sep).join("/"));
    } catch { /* read-only checkout etc. — doctor reports stale copies */ }
  };

  // 1. MCP server copies. Current location is .cursor/; versions before the
  //    .cursor/ move wrote ./inferno-mcp-server.mjs at the project root.
  const serverTemplate = readOrNull(path.join(tmpl, "cursor", "inferno-mcp-server.mjs"));
  if (serverTemplate) {
    for (const rel of [path.join(".cursor", "inferno-mcp-server.mjs"), "inferno-mcp-server.mjs"]) {
      const current = readOrNull(path.join(cwd, rel));
      if (current == null) continue;                          // not installed here
      if (!looksLikeInfernoflowServer(current)) continue;     // someone else's file
      if (norm(current) === norm(serverTemplate)) continue;   // already current
      rewrite(rel, serverTemplate);
    }
  }

  // 2. Cursor prompt hook.
  const cursorHookTemplate = readOrNull(path.join(tmpl, "cursor", "hooks", "inferno-session-draft.mjs"));
  if (cursorHookTemplate) {
    const rel = path.join(".cursor", "hooks", "inferno-session-draft.mjs");
    const current = readOrNull(path.join(cwd, rel));
    if (current != null && !current.includes(HOOK_VERSION_MARKER)) rewrite(rel, cursorHookTemplate);
  }

  // 3. Claude Code prompt hook.
  if (opts.captureHookScript) {
    const rel = path.join(".claude", "hooks", "log-frustration.mjs");
    const current = readOrNull(path.join(cwd, rel));
    if (current != null && !current.includes(HOOK_VERSION_MARKER)) rewrite(rel, opts.captureHookScript);
  }

  return updated;
}
