/**
 * infernoflow ci
 *
 * Auto-detect the CI environment and output structured annotations that
 * integrate natively with each platform's UI.
 *
 * Supported platforms:
 *   GitHub Actions   → ::error:: / ::warning:: / step summary (GITHUB_STEP_SUMMARY)
 *   GitLab CI        → gl-code-quality.json artifact
 *   Bitbucket        → annotations API via curl
 *   Generic          → exit code + JSON output (for any CI)
 *
 * Usage:
 *   infernoflow ci                     Auto-detect platform, run check + diff
 *   infernoflow ci --platform github   Force a platform
 *   infernoflow ci --fail-on warning   Fail on warning or higher (default: error)
 *   infernoflow ci --json              Machine-readable result
 *
 * Exits 0 on success, 1 on error/warning (based on --fail-on).
 */

import * as fs   from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { header, ok, warn, info, done, bold, cyan, gray, green, red, yellow } from "../ui/output.mjs";

// ── Platform detection ────────────────────────────────────────────────────────

function detectPlatform() {
  if (process.env.GITHUB_ACTIONS === "true")       return "github";
  if (process.env.GITLAB_CI === "true")            return "gitlab";
  if (process.env.BITBUCKET_BUILD_NUMBER)          return "bitbucket";
  if (process.env.CIRCLECI === "true")             return "circleci";
  if (process.env.JENKINS_URL)                     return "jenkins";
  if (process.env.CI === "true")                   return "generic";
  return "local";
}

// ── CLI runner ────────────────────────────────────────────────────────────────

function runJson(command, cwd) {
  try {
    const [bin, ...args] = command.split(" ");
    const result = spawnSync(process.execPath, [
      path.join(path.dirname(path.dirname(fileURLToPath(import.meta.url))), "..", "bin", "infernoflow.mjs"),
      ...command.split(" ").slice(1)
    ], { cwd, encoding: "utf8", timeout: 30_000 });
    const out = result.stdout?.trim();
    if (out) return JSON.parse(out);
  } catch {}
  return null;
}

function runCli(args, cwd) {
  try {
    const result = spawnSync(process.execPath, [
      path.join(path.dirname(path.dirname(fileURLToPath(import.meta.url))), "..", "bin", "infernoflow.mjs"),
      ...args
    ], { cwd, encoding: "utf8", timeout: 30_000 });
    return result.stdout?.trim() || "";
  } catch { return ""; }
}

// ── GitHub Actions output ─────────────────────────────────────────────────────

function emitGithub(checkResult, diffResult, failOn) {
  const status = checkResult?.status || "unknown";
  const issues = checkResult?.issues || [];
  const caps   = checkResult?.capabilities || 0;
  const added  = diffResult?.added?.length || 0;
  const removed = diffResult?.removed?.length || 0;
  const changed = diffResult?.changed?.length || 0;

  // GitHub workflow commands
  if (status === "error") {
    issues.filter(i => i.severity === "error").forEach(i => {
      console.log(`::error::infernoflow: ${i.message}`);
    });
  } else if (status === "warning") {
    issues.filter(i => i.severity === "warning").forEach(i => {
      console.log(`::warning::infernoflow: ${i.message}`);
    });
  }

  if (added > 0)   console.log(`::notice::infernoflow: ${added} new capability${added !== 1 ? "ies" : "y"} added`);
  if (removed > 0) console.log(`::warning::infernoflow: ${removed} capability${removed !== 1 ? "ies" : "y"} removed`);

  // Step summary
  const summaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (summaryPath) {
    const statusIcon = status === "ok" ? "✅" : status === "warning" ? "⚠️" : "❌";
    const lines = [
      `## 🔥 infernoflow CI report`,
      "",
      `${statusIcon} **Status:** ${status.toUpperCase()}  ·  **Capabilities:** ${caps}`,
      "",
    ];
    if (added || removed || changed) {
      lines.push("### Capability changes");
      if (added)   lines.push(`- ✅ **${added}** added`);
      if (removed) lines.push(`- ❌ **${removed}** removed`);
      if (changed) lines.push(`- 📝 **${changed}** changed`);
      lines.push("");
    }
    if (issues.length) {
      lines.push("### Issues");
      issues.forEach(i => lines.push(`- **${i.severity?.toUpperCase() || "INFO"}**: ${i.message}`));
      lines.push("");
    }
    lines.push("---");
    lines.push("*Generated by [infernoflow](https://github.com/ronmiz/infernoflow)*");
    try { fs.appendFileSync(summaryPath, lines.join("\n") + "\n"); } catch {}
  }
}

// ── GitLab code quality report ────────────────────────────────────────────────

function emitGitlab(checkResult, cwd) {
  const issues = checkResult?.issues || [];
  const report = issues.map((issue, i) => ({
    description:      issue.message || "infernoflow issue",
    fingerprint:      Buffer.from(`infernoflow-${i}-${issue.message}`).toString("hex").slice(0, 40),
    severity:         issue.severity === "error" ? "critical" : "minor",
    location: {
      path:       "inferno/contract.json",
      lines:      { begin: 1 },
    },
  }));
  const reportPath = path.join(cwd, "gl-code-quality-report.json");
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));
  console.log(`infernoflow: GitLab code quality report written → gl-code-quality-report.json`);
}

// ── Generic CI output ─────────────────────────────────────────────────────────

function emitGeneric(checkResult, diffResult, platform) {
  const status = checkResult?.status || "unknown";
  const caps   = checkResult?.capabilities || 0;
  const added  = diffResult?.added?.length || 0;
  const removed = diffResult?.removed?.length || 0;

  console.log(`[infernoflow] platform=${platform} status=${status} capabilities=${caps} added=${added} removed=${removed}`);
  if (checkResult?.issues?.length) {
    checkResult.issues.forEach(i => {
      console.log(`[infernoflow] ${(i.severity || "info").toUpperCase()}: ${i.message}`);
    });
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

export async function ciCommand(rawArgs) {
  const args        = rawArgs.slice(1);
  const jsonMode    = args.includes("--json");
  const platformArg = args.includes("--platform") ? args[args.indexOf("--platform") + 1] : null;
  const failOn      = args.includes("--fail-on") ? args[args.indexOf("--fail-on") + 1] : "error";
  const cwd         = process.cwd();
  const infernoDir  = path.join(cwd, "inferno");

  if (!fs.existsSync(infernoDir)) {
    if (jsonMode) { console.log(JSON.stringify({ ok: false, error: "inferno/ not found" })); }
    else { console.log("[infernoflow] inferno/ not found — skipping CI check"); }
    process.exit(0); // Don't block CI if infernoflow isn't set up
  }

  const platform = platformArg || detectPlatform();

  if (!jsonMode) {
    console.log(`[infernoflow] running CI check (platform: ${platform})`);
  }

  // Run check + diff
  const checkResult = runJson("check --json", cwd);
  const diffResult  = runJson("diff --json", cwd);
  const status      = checkResult?.status || "unknown";

  // Platform-specific output
  switch (platform) {
    case "github":
      emitGithub(checkResult, diffResult, failOn);
      break;
    case "gitlab":
      emitGitlab(checkResult, cwd);
      emitGeneric(checkResult, diffResult, platform);
      break;
    default:
      emitGeneric(checkResult, diffResult, platform);
  }

  if (jsonMode) {
    console.log(JSON.stringify({
      ok:       status === "ok" || status === "warning",
      platform,
      status,
      capabilities: checkResult?.capabilities || 0,
      issues:   checkResult?.issues || [],
      diff:     { added: diffResult?.added || [], removed: diffResult?.removed || [], changed: diffResult?.changed || [] },
    }));
  }

  // Exit code
  const shouldFail = failOn === "warning"
    ? (status === "error" || status === "warning")
    : (status === "error");

  process.exit(shouldFail ? 1 : 0);
}
