import path from "node:path";
import { execSync } from "node:child_process";
import { bold, gray, cyan, red, green, yellow } from "../ui/output.mjs";

function copyToClipboard(text) {
  try {
    const p = process.platform;
    if (p === "win32") execSync("clip", { input: text });
    else if (p === "darwin") execSync("pbcopy", { input: text });
    else { try { execSync("xclip -selection clipboard", { input: text }); } catch { execSync("xsel --clipboard --input", { input: text }); } }
    return true;
  } catch { return false; }
}

const INFERNO_DIR = "inferno";
const CONTEXT_FILE = path.join(INFERNO_DIR, "CONTEXT.md");
const STATE_FILE  = path.join(INFERNO_DIR, "context-state.json");

function readJSON(f) { try { return JSON.parse(fs.readFileSync(f,"utf8")); } catch { return null; } }
function readFile(f) { try { return fs.readFileSync(f,"utf8"); } catch { return null; } }
function loadState() { const r=readFile(STATE_FILE); if(!r) return {}; try { return JSON.parse(r); } catch { return {}; } }
function saveState(s) { fs.writeFileSync(STATE_FILE,JSON.stringify(s,null,2),"utf8"); }
function fmtDate(iso) { if(!iso) return "unknown"; return new Date(iso).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}); }
function parseChangelog(txt,max) {
  if(!txt) return [];
  const entries=[]; let cur=null;
  for(const line of txt.split("\n")) {
    if(line.startsWith("## ")) { if(cur&&entries.length<max) entries.push(cur); if(entries.length>=max) break; cur={title:line.replace("## ","").trim(),items:[]}; }
    else if(cur&&line.startsWith("- ")) cur.items.push(line.replace("- ","").trim());
  }
  if(cur&&entries.length<max) entries.push(cur);
  return entries.filter(e=>e.items.length>0);
}

export async function contextCommand(args) {
  const has  = (f) => args.includes(f);
  const flag = (f) => { const i=args.indexOf(f); return i!==-1&&args[i+1]?args[i+1]:null; };

  const intent   = flag("--intent")   || flag("-i");
  const working  = flag("--working")  || flag("-w");
  const decision = flag("--decision") || flag("-d");
  const showOnly = has("--show")  || has("-s");
  const copyFlag = has("--copy")  || has("-c");
  const resetFlag= has("--reset");

  console.log("\n  "+bold("��� infernoflow — context"));
  console.log("  "+"─".repeat(50)+"\n");

  if(!fs.existsSync(INFERNO_DIR)){
    console.error(red("  ✘ inferno/ not found"));
    console.error(gray("  → Run: infernoflow init\n"));
    process.exit(1);
  }

  const contract     = readJSON(path.join(INFERNO_DIR,"contract.json"));
  const capabilities = readJSON(path.join(INFERNO_DIR,"capabilities.json"));
  const changelog    = readFile(path.join(INFERNO_DIR,"CHANGELOG.md"));

  if(!contract||!capabilities){
    console.error(red("  ✘ Missing contract.json or capabilities.json\n"));
    process.exit(1);
  }

  let state = loadState();
  if(resetFlag){ state={}; console.log(yellow("  ⚠ State reset\n")); }
  if(intent)   { state.intent=intent; state.intentUpdated=new Date().toISOString(); console.log(green('  ✔ Intent saved: "'+intent+'"')); }
  if(working)  { state.working=working; state.workingUpdated=new Date().toISOString(); console.log(green('  ✔ Working on: "'+working+'"')); }
  if(decision) { if(!state.decisions) state.decisions=[]; state.decisions.push({text:decision,date:new Date().toISOString()}); console.log(green('  ✔ Decision recorded: "'+decision+'"')); }
  if(intent||working||decision) saveState(state);

  const capList   = capabilities.capabilities||[];
  const allInSync = capList.length===(contract.capabilities||[]).length;
  const recent    = parseChangelog(changelog,3);
  const version   = String(contract.policyVersion).replace(/^v/i,"");
  const now       = new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});
  const syncBadge = allInSync?"✓ validated":"⚠ out of sync";

  const capLines  = capList.map(c=>"- **"+c.id+"** — "+c.title).join("\n");
  const chgLines  = recent.length>0 ? recent.map(e=>"### "+e.title+"\n"+e.items.map(i=>"  - "+i).join("\n")).join("\n\n") : "_No recent changes_";
  const intentLine  = state.intent   ? state.intent+"  _("+fmtDate(state.intentUpdated)+")_"  : "_Not set — run: infernoflow context --intent \"...\"_";
  const workingLine = state.working  ? state.working+"  _("+fmtDate(state.workingUpdated)+")_" : "_Not set — run: infernoflow context --working \"...\"_";
  const decLines    = state.decisions&&state.decisions.length>0 ? state.decisions.slice(-5).map(d=>"- "+d.text+"  _("+fmtDate(d.date)+")_").join("\n") : "_No decisions recorded_";

  const md = [
    "# Project Context — "+contract.policyId+" v"+version,
    "> Generated by infernoflow | "+now+" | "+syncBadge,
    "","---","",
    "## What this system does","",capLines,"","---","",
    "## Recent changes","",chgLines,"","---","",
    "## Current state","",
    "- **Capabilities:** "+capList.length,
    "- **Version:** v"+version,
    "- **Sync:** "+syncBadge,
    "","---","",
    "## What I am working on right now","",workingLine,"","---","",
    "## Intent — what I want to build next","",intentLine,"","---","",
    "## Decisions & notes","",decLines,"","---",
    "_Paste this block at the start of any new AI session._"
  ].join("\n");

  if(!showOnly){ fs.writeFileSync(CONTEXT_FILE,md,"utf8"); console.log(green("\n  ✔ Context written → "+CONTEXT_FILE)); }

  if(copyFlag){
    const ok=copyToClipboard(md);
    console.log(ok ? green("  ✔ Copied to clipboard — paste with Ctrl+V") : yellow("  ⚠ Clipboard copy failed — open inferno/CONTEXT.md manually"));
  }

  console.log("\n  "+bold("Context Summary"));
  console.log("  "+"─".repeat(50));
  console.log("  Project      "+contract.policyId+" — v"+version);
  console.log("  Capabilities "+capList.length+" registered");
  console.log("  Sync         "+(allInSync?green("✓ in sync"):yellow("⚠ check needed")));
  console.log("  Working on   "+(state.working?cyan(state.working):gray("not set")));
  console.log("  Intent       "+(state.intent ?cyan(state.intent) :gray("not set")));
  console.log("  Decisions    "+(state.decisions?state.decisions.length:0)+" recorded\n");

  if(copyFlag){
    console.log("  "+bold("Ready to use:"));
    console.log("  "+cyan("→")+" Paste into Claude / Cursor / Copilot with "+cyan("Ctrl+V")+"\n");
  } else {
    console.log("  "+bold("Ready to use:"));
    console.log("  "+cyan("1.")+" Open "+cyan("inferno/CONTEXT.md"));
    console.log("  "+cyan("2.")+" Copy everything");
    console.log("  "+cyan("3.")+" Paste at the start of your next AI session");
    console.log("  "+gray("  tip: use --copy to skip steps 1-2 automatically")+"\n");
  }
}
