import fs from "node:fs";
import path from "node:path";
import { bold, gray, cyan, red, green, yellow } from "../ui/output.mjs";

const INFERNO_DIR = "inferno";
const CONTEXT_FILE = path.join(INFERNO_DIR, "CONTEXT.md");
const STATE_FILE = path.join(INFERNO_DIR, "context-state.json");

function readJSON(filePath) {
  try { return JSON.parse(fs.readFileSync(filePath, "utf8")); }
  catch { return null; }
}

function readFile(filePath) {
  try { return fs.readFileSync(filePath, "utf8"); }
  catch { return null; }
}

function parseRecentChangelog(changelogContent, maxEntries = 3) {
  if (!changelogContent) return [];
  const lines = changelogContent.split("\n");
  const entries = [];
  let current = null;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current && entries.length < maxEntries) entries.push(current);
      if (entries.length >= maxEntries) break;
      current = { title: line.replace("## ", "").trim(), items: [] };
    } else if (current && line.startsWith("- ")) {
      current.items.push(line.replace("- ", "").trim());
    }
  }
  if (current && entries.length < maxEntries) entries.push(current);
  return entries.filter(e => e.items.length > 0);
}

function loadState() {
  const raw = readFile(STATE_FILE);
  if (!raw) return {};
  try { return JSON.parse(raw); } catch { return {}; }
}

function saveState(state) {
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2), "utf8");
}

function formatDate(iso) {
  if (!iso) return "unknown";
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "2-digit", month: "short", year: "numeric"
  });
}

export async function contextCommand(args) {
  const getFlagValue = (f) => {
    const i = args.indexOf(f);
    return i !== -1 && args[i + 1] ? args[i + 1] : null;
  };
  const hasFlag = (f) => args.includes(f);

  const intent   = getFlagValue("--intent")   || getFlagValue("-i");
  const working  = getFlagValue("--working")  || getFlagValue("-w");
  const decision = getFlagValue("--decision") || getFlagValue("-d");
  const showOnly = hasFlag("--show") || hasFlag("-s");
  const resetState = hasFlag("--reset");

  console.log(`\n  ${bold("🔥 infernoflow — context")}`);
  console.log(`  ${"─".repeat(50)}\n`);

  if (!fs.existsSync(INFERNO_DIR)) {
    console.error(red("  ✘ inferno/ not found"));
    console.error(gray("  → Run: infernoflow init\n"));
    process.exit(1);
  }

  const contract     = readJSON(path.join(INFERNO_DIR, "contract.json"));
  const capabilities = readJSON(path.join(INFERNO_DIR, "capabilities.json"));
  const changelog    = readFile(path.join(INFERNO_DIR, "CHANGELOG.md"));

  if (!contract || !capabilities) {
    console.error(red("  ✘ Missing contract.json or capabilities.json"));
    process.exit(1);
  }

  let state = loadState();
  if (resetState) { state = {}; console.log(yellow("  ⚠ State reset\n")); }

  if (intent)   { state.intent = intent; state.intentUpdated = new Date().toISOString(); console.log(green(`  ✔ Intent saved: "${intent}"`)); }
  if (working)  { state.working = working; state.workingUpdated = new Date().toISOString(); console.log(green(`  ✔ Working on: "${working}"`)); }
  if (decision) {
    if (!state.decisions) state.decisions = [];
    state.decisions.push({ text: decision, date: new Date().toISOString() });
    console.log(green(`  ✔ Decision recorded: "${decision}"`));
  }
  if (intent || working || decision) saveState(state);

  const capList      = capabilities.capabilities || [];
  const contractCaps = contract.capabilities || [];
  const allInSync    = capList.length === contractCaps.length;
  const recentChanges = parseRecentChangelog(changelog, 3);

  const now = new Date().toLocaleDateString("en-GB", {
    day: "2-digit", month: "short", year: "numeric"
  });

  const capLines = capList.map(c => `- **${c.id}** — ${c.title}`).join("\n");

  const changelogLines = recentChanges.length > 0
    ? recentChanges.map(e => `### ${e.title}\n${e.items.map(i => `  - ${i}`).join("\n")}`).join("\n\n")
    : "_No recent changes recorded_";

  const intentLine  = state.intent
    ? `${state.intent}  _(updated: ${formatDate(state.intentUpdated)})_`
    : "_Not set — run: `infernoflow context --intent \"what I want to do next\"`_";

  const workingLine = state.working
    ? `${state.working}  _(updated: ${formatDate(state.workingUpdated)})_`
    : "_Not set — run: `infernoflow context --working \"what I am building now\"`_";

  const decisionsLines = state.decisions?.length > 0
    ? state.decisions.slice(-5).map(d => `- ${d.text}  _(${formatDate(d.date)})_`).join("\n")
    : "_No decisions recorded — run: `infernoflow context --decision \"why I chose X\"`_";

  const syncBadge = allInSync ? "✓ validated" : "⚠ out of sync — run infernoflow check";
  const version   = String(contract.policyVersion).replace(/^v/i, "");

  const contextMd = `# Project Context — ${contract.policyId} v${version}
> Generated by infernoflow | ${now} | ${syncBadge}

---

## What this system does

${capLines}

---

## Recent changes

${changelogLines}

---

## Current state

- **Capabilities declared:** ${capList.length}
- **Contract version:** v${version}
- **Sync status:** ${syncBadge}

---

## What I am working on right now

${workingLine}

---

## Intent — what I want to build next

${intentLine}

---

## Decisions & notes

${decisionsLines}

---
_Paste this block at the start of any new AI session